import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";
import Header from "@/components/common/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-Pretendard text-black">
      <AuthContext>
        <body className={inter.className && `flex flex-col w-full h-screen`}>
          <Header />
          <div className="w-full h-full">
            {children}
          </div>
        </body>
      </AuthContext>
    </html>
  );
}
